<?php

namespace bensomething\daemon\tests;

use bensomething\daemon\models\Settings;
use PHPUnit\Framework\TestCase;

/**
 * Covers the normalisation the settings screen depends on. Names arrive from a
 * form, one field per WAD, so most of them arrive empty on every save.
 */
class SettingsTest extends TestCase
{
    public function testTrimsNames(): void
    {
        $this->assertSame(
            ['doom1' => 'Knee-Deep in the Dead'],
            $this->normalize(['doom1' => '   Knee-Deep in the Dead   ']),
        );
    }

    /**
     * An untouched field posts an empty string. Storing it would write
     * `doom1: ''` into project config on every save, which reads as a WAD
     * called nothing rather than a WAD with no custom name.
     */
    public function testDropsBlankNames(): void
    {
        $this->assertSame(
            ['doom2' => 'Hell on Earth'],
            $this->normalize(['doom1' => '', 'doom2' => 'Hell on Earth', 'doom3' => '   ']),
        );
    }

    /**
     * Keys are generated by the WAD service and never typed, so anything not
     * shaped like one of its keys did not come from this screen.
     *
     * @dataProvider badKeys
     */
    public function testDropsKeysItCouldNotHaveIssued(string $key): void
    {
        $this->assertSame([], $this->normalize([$key => 'name']));
    }

    /**
     * @return array<string, string[]>
     */
    public static function badKeys(): array
    {
        return [
            'traversal' => ['../evil'],
            'path' => ['a/b'],
            'uppercase' => ['DOOM1'],
            'empty' => [''],
            'leading dash' => ['-doom'],
            'too long' => [str_repeat('a', 65)],
        ];
    }

    /**
     * The field is a textarea, so a pasted name can arrive with newlines and
     * runs of whitespace in it. A game called "Doom\n\nII" is not a name.
     */
    public function testCollapsesWhitespace(): void
    {
        $this->assertSame(
            ['doom2' => 'Hell on Earth'],
            $this->normalize(['doom2' => "Hell\n  on\tEarth"]),
        );
    }

    public function testSortsForAStableProjectConfig(): void
    {
        $this->assertSame(
            ['alpha', 'beta', 'gamma'],
            array_keys($this->normalize(['gamma' => 'c', 'alpha' => 'a', 'beta' => 'b'])),
        );
    }

    /**
     * @dataProvider badKeys
     */
    public function testRejectsADefaultItCouldNotHaveIssued(string $key): void
    {
        $settings = new Settings();
        $settings->defaultWad = $key;
        $settings->beforeValidate();

        $this->assertNull($settings->defaultWad);
    }

    public function testKeepsAUsableDefault(): void
    {
        $settings = new Settings();
        $settings->defaultWad = ' freedoom2 ';
        $settings->beforeValidate();

        $this->assertSame('freedoom2', $settings->defaultWad);
    }

    /**
     * @param array<string, string> $names
     * @return array<string, string>
     */
    private function normalize(array $names): array
    {
        $settings = new Settings();
        $settings->wadNames = $names;
        $settings->beforeValidate();

        return $settings->wadNames;
    }
}
