<?php

namespace bensomething\daemon\models;

use Craft;
use craft\base\Model;
use craft\helpers\App;
use craft\helpers\FileHelper;

class Settings extends Model
{
    /**
     * @var string|null A directory to look for WADs in, as an alias or an env
     * var reference. Null means storage/daemon/ only.
     */
    public ?string $wadDir = null;

    /**
     * @var string|null The key of the WAD to load when nothing else is asked
     * for. Null means the first one found, which is alphabetical within the
     * first search directory and therefore decided by accident.
     *
     * A key that names nothing available is ignored rather than treated as an
     * error: the same setting is deployed to environments whose storage holds
     * a different set of WADs.
     */
    public ?string $defaultWad = null;

    /**
     * @var array<string, string> Names the admin has given WADs, keyed by the
     * WAD key. Anything absent falls back to the name the plugin derives from
     * the filename.
     *
     * Keyed by the WAD key, which comes from the filename, so renaming a file
     * orphans its name. That beats keying on the full path, which orphans on
     * every environment whose storage lives somewhere else.
     */
    public array $wadNames = [];

    /**
     * @var bool Whether savegames are copied into Craft as the engine writes
     * them, which also decides whether the Saves menu appears at all. Off
     * leaves saves in the browser, where the engine puts them, and the only
     * thing standing between a player and a lost level is the warning shown
     * when leaving the page.
     */
    public bool $autosave = false;

    /**
     * @var bool Whether pointer lock is offered for mouselook. Off means
     * keyboard only, which some people prefer and some browsers force.
     */
    public bool $pointerLock = true;

    /**
     * The configured directory with any $ENV_VAR or @alias resolved. Null when
     * nothing is configured, and also when the reference resolves to nothing,
     * which is what a $VAR set in one environment and not another does. That
     * is the quiet outcome on purpose: the plugin falls back to storage rather
     * than complaining about a path this environment was never meant to have.
     */
    public function getWadDir(): ?string
    {
        if ($this->wadDir === null || trim($this->wadDir) === '') {
            return null;
        }

        // parseEnv resolves an @alias as well as a $VAR, so nothing further is
        // needed here.
        $dir = App::parseEnv($this->wadDir);

        if (!is_string($dir) || $dir === '') {
            return null;
        }

        $dir = FileHelper::normalizePath($dir);

        return $dir !== '' ? $dir : null;
    }

    /**
     * Drops blank and unusable entries before validation.
     *
     * A field left empty posts an empty string, and storing that would put
     * `key: ''` into project config on every save, which reads as "this WAD is
     * called nothing" rather than "this WAD has no custom name".
     */
    public function beforeValidate(): bool
    {
        $defaultWad = trim((string)$this->defaultWad);
        $this->defaultWad = $this->isWadKey($defaultWad) ? $defaultWad : null;

        $names = [];

        foreach ($this->wadNames as $key => $name) {
            $key = (string)$key;

            // The field is a textarea, because that is what Craft's editable
            // table uses for a single-line cell, so it can hold newlines and a
            // pasted name can arrive with any amount of whitespace in it.
            $name = trim((string)preg_replace('/\s+/', ' ', (string)$name));

            // Keys are generated by the WAD service, so anything that isn't
            // shaped like one of its keys was not put there by this screen.
            if ($name === '' || !$this->isWadKey($key)) {
                continue;
            }

            $names[$key] = $name;
        }

        ksort($names);
        $this->wadNames = $names;

        return parent::beforeValidate();
    }

    /**
     * Whether a string is shaped like a key the WAD service issues. Keys are
     * generated, never typed, so anything else did not come from the settings
     * screen.
     */
    private function isWadKey(string $key): bool
    {
        return (bool)preg_match('/^[a-z0-9][a-z0-9-]{0,63}$/', $key);
    }

    protected function defineRules(): array
    {
        return [
            [['wadDir'], 'trim'],
            [['wadDir'], 'string'],
            [['defaultWad'], 'string'],
            [['autosave', 'pointerLock'], 'boolean'],
            [['wadNames'], 'validateWadNames'],
        ];
    }

    /**
     * Checks that every name is a string of a sane length. beforeValidate()
     * has already dropped the blanks and the keys this screen can't produce,
     * so anything left that fails here arrived some other way.
     */
    public function validateWadNames(string $attribute): void
    {
        foreach ($this->$attribute as $key => $name) {
            if (!is_string($name) || mb_strlen($name) > 255) {
                $this->addError($attribute, Craft::t('daemon', 'The name for {key} is not usable.', [
                    'key' => $key,
                ]));
            }
        }
    }
}
