<?php

namespace bensomething\daemon\models;

use Craft;
use craft\base\Model;
use craft\helpers\App;
use craft\helpers\FileHelper;

class Settings extends Model
{
    /**
     * @var string|null A directory to look for WADs in, as an alias or an env var
     * reference. Null means storage/daemon/ only.
     */
    public ?string $wadDir = null;

    /**
     * @var string|null The key of the WAD to load when nothing else is asked for.
     * Null means the first one found. A key naming nothing available is ignored
     * rather than an error: the same setting reaches environments holding other WADs.
     */
    public ?string $defaultWad = null;

    /**
     * @var array<string, string> Names the admin has given WADs, keyed by the WAD
     * key, which comes from the filename. Anything absent falls back to the derived
     * name. Renaming a file orphans its name, which beats keying on the full path.
     */
    public array $wadNames = [];

    /**
     * @var bool Whether savegames are copied into Craft as the engine writes them,
     * which also decides whether the Saves menu appears. Off leaves them in the
     * browser, with only the unload warning between a player and a lost level.
     */
    public bool $autosave = false;

    /** @var bool Whether pointer lock is offered for mouselook. */
    public bool $pointerLock = true;

    /**
     * The configured directory with any $ENV_VAR or @alias resolved. Null when
     * nothing is configured, and when the reference resolves to nothing, which is
     * what a $VAR set in one environment and not another does. Quiet on purpose:
     * the plugin falls back to storage rather than complaining.
     */
    public function getWadDir(): ?string
    {
        if ($this->wadDir === null || trim($this->wadDir) === '') {
            return null;
        }

        // parseEnv resolves an @alias as well as a $VAR, so nothing further is
        // needed here.
        $dir = App::parseEnv($this->wadDir);

        if (!is_string($dir) || $dir === '') {
            return null;
        }

        $dir = FileHelper::normalizePath($dir);

        return $dir !== '' ? $dir : null;
    }

    /**
     * Drops blank and unusable entries before validation. An empty field posts an
     * empty string, and storing that reads as "this WAD is called nothing".
     */
    public function beforeValidate(): bool
    {
        $defaultWad = trim((string)$this->defaultWad);
        $this->defaultWad = $this->isWadKey($defaultWad) ? $defaultWad : null;

        $names = [];

        foreach ($this->wadNames as $key => $name) {
            $key = (string)$key;

            // The field is a textarea, because that is what Craft's editable
            // table uses for a single-line cell, so it can hold newlines and a
            // pasted name can arrive with any amount of whitespace in it.
            $name = trim((string)preg_replace('/\s+/', ' ', (string)$name));

            // Keys are generated by the WAD service, so anything that isn't
            // shaped like one of its keys was not put there by this screen.
            if ($name === '' || !$this->isWadKey($key)) {
                continue;
            }

            $names[$key] = $name;
        }

        ksort($names);
        $this->wadNames = $names;

        return parent::beforeValidate();
    }

    /**
     * Whether a string is shaped like a key the WAD service issues. Keys are
     * generated, never typed.
     */
    private function isWadKey(string $key): bool
    {
        return (bool)preg_match('/^[a-z0-9][a-z0-9-]{0,63}$/', $key);
    }

    protected function defineRules(): array
    {
        return [
            [['wadDir'], 'trim'],
            [['wadDir'], 'string'],
            [['defaultWad'], 'string'],
            [['autosave', 'pointerLock'], 'boolean'],
            [['wadNames'], 'validateWadNames'],
        ];
    }

    /**
     * Checks that every name is a string of a sane length. beforeValidate() has
     * already dropped the blanks and the keys this screen can't produce.
     */
    public function validateWadNames(string $attribute): void
    {
        foreach ($this->$attribute as $key => $name) {
            if (!is_string($name) || mb_strlen($name) > 255) {
                $this->addError($attribute, Craft::t('daemon', 'The name for {key} is not usable.', [
                    'key' => $key,
                ]));
            }
        }
    }
}
